name: mysql

networks:
  # Network
  mysql:
    driver: bridge

services:
  # DB server
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # 管理者用のパスワード
      MYSQL_USER: 'student' # 研修参加者用ユーザー名
      MYSQL_PASSWORD: 'password' # 参加者用パスワード
      MYSQL_DATABASE: 'training_db' # 研修用データベース名
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
      - type: bind
        source: ./config/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./logs
        target: /var/log/mysql
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
    networks:
      - mysql
